//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TimGcpSmSecret) DeepCopyInto(out *TimGcpSmSecret) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TimGcpSmSecret.
func (in *TimGcpSmSecret) DeepCopy() *TimGcpSmSecret {
	if in == nil {
		return nil
	}
	out := new(TimGcpSmSecret)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TimGcpSmSecret) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TimGcpSmSecretList) DeepCopyInto(out *TimGcpSmSecretList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]TimGcpSmSecret, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TimGcpSmSecretList.
func (in *TimGcpSmSecretList) DeepCopy() *TimGcpSmSecretList {
	if in == nil {
		return nil
	}
	out := new(TimGcpSmSecretList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TimGcpSmSecretList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TimGcpSmSecretSpec) DeepCopyInto(out *TimGcpSmSecretSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TimGcpSmSecretSpec.
func (in *TimGcpSmSecretSpec) DeepCopy() *TimGcpSmSecretSpec {
	if in == nil {
		return nil
	}
	out := new(TimGcpSmSecretSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TimGcpSmSecretStatus) DeepCopyInto(out *TimGcpSmSecretStatus) {
	*out = *in
	if in.LastSyncTime != nil {
		in, out := &in.LastSyncTime, &out.LastSyncTime
		*out = (*in).DeepCopy()
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TimGcpSmSecretStatus.
func (in *TimGcpSmSecretStatus) DeepCopy() *TimGcpSmSecretStatus {
	if in == nil {
		return nil
	}
	out := new(TimGcpSmSecretStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TimGcpSmSecretConfig) DeepCopyInto(out *TimGcpSmSecretConfig) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TimGcpSmSecretConfig.
func (in *TimGcpSmSecretConfig) DeepCopy() *TimGcpSmSecretConfig {
	if in == nil {
		return nil
	}
	out := new(TimGcpSmSecretConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TimGcpSmSecretConfig) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TimGcpSmSecretConfigList) DeepCopyInto(out *TimGcpSmSecretConfigList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]TimGcpSmSecretConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TimGcpSmSecretConfigList.
func (in *TimGcpSmSecretConfigList) DeepCopy() *TimGcpSmSecretConfigList {
	if in == nil {
		return nil
	}
	out := new(TimGcpSmSecretConfigList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TimGcpSmSecretConfigList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TimGcpSmSecretConfigSpec) DeepCopyInto(out *TimGcpSmSecretConfigSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TimGcpSmSecretConfigSpec.
func (in *TimGcpSmSecretConfigSpec) DeepCopy() *TimGcpSmSecretConfigSpec {
	if in == nil {
		return nil
	}
	out := new(TimGcpSmSecretConfigSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TimGcpSmClusterConfig) DeepCopyInto(out *TimGcpSmClusterConfig) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TimGcpSmClusterConfig.
func (in *TimGcpSmClusterConfig) DeepCopy() *TimGcpSmClusterConfig {
	if in == nil {
		return nil
	}
	out := new(TimGcpSmClusterConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TimGcpSmClusterConfig) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TimGcpSmClusterConfigList) DeepCopyInto(out *TimGcpSmClusterConfigList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]TimGcpSmClusterConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TimGcpSmClusterConfigList.
func (in *TimGcpSmClusterConfigList) DeepCopy() *TimGcpSmClusterConfigList {
	if in == nil {
		return nil
	}
	out := new(TimGcpSmClusterConfigList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TimGcpSmClusterConfigList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TimGcpSmClusterConfigSpec) DeepCopyInto(out *TimGcpSmClusterConfigSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TimGcpSmClusterConfigSpec.
func (in *TimGcpSmClusterConfigSpec) DeepCopy() *TimGcpSmClusterConfigSpec {
	if in == nil {
		return nil
	}
	out := new(TimGcpSmClusterConfigSpec)
	in.DeepCopyInto(out)
	return out
}
