apiVersion: secrets.tim.operator/v1alpha1
kind: TimGcpSmSecret
metadata:
  name: example-app-secrets
  namespace: default
spec:
  projectId: my-gcp-project
  secretId: my-gsm-secret
  secretName: example-app-secrets
  syncInterval: 2m
