apiVersion: secrets.tim.operator/v1alpha1
kind: TimGcpSmSecret
metadata:
  name: example-app-secrets
  namespace: default
spec:
  gcpSmConfig: gcp-default
  secretId: my-gsm-secret
  secretName: example-app-secrets
  deploymentName: example-app
